name: Generate Datas

on:
  schedule: # execute every 12 hours
    - cron: "* */12 * * *"
  workflow_dispatch:
  
# run on every push on the master branch
  push:
    branches:
    - main

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      # Snake Animation
      - name: generate github-contribution-grid-snake.svg
      - uses: Platane/snk/svg-only@v2
        id: snake-gif
        with:
          github_user_name: Javoso
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
        
      - name: push github-contribution-grid-snake.svg to the output branch
      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
